### ISSUE TITLE
Readme 파일 수정 - 유희진

### ISSUE THREAD

**Issue by barabobBOB** [team-g-techeer/In-For-Plan#4]
표 양식에 맞춰서 작성해주시면 됩니다.

- [x] 이름
- [x] role
- [x] githublink

**Comment by yu-heejin** [comment]
| Name    |                                        |유희진                              |                                      |                                    |
| ------- | --------------------------------------------- | ------------------------------------ | --------------------------------------------- | --------------------------------------- |
| role    |                 |Backend & Frontend                          |                                  |  |
| Github  |  |[@yu-heejin ](https://github.com/yu-heejin)  |  |  |
